### ISSUE TITLE
Msbuild Issue

### ISSUE THREAD

**Issue by Saikartik19** [felixrieseberg/windows-build-tools#101]
Here is my Package JSON 
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "postinstall": "electron-builder install-app-deps"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "~1.8.2",
    "electron-builder": "^20.5.1",
    "electron-rebuild": "^1.7.3"
  },
  "dependencies": {
    "build": "^0.1.4",
    "clean": "^4.0.2",
    "jquery": "^3.3.1",
    "node-gyp": "^3.6.2",
    "portscanner": "^2.1.1",
    "save": "^2.3.2",
    "sqlite3": "^4.0.0",
    "uuid": "^3.2.1",
    "websocket": "^1.0.25",
    "windows-build-tools": "^2.2.1"
  }
}

On npm run postinstall I'm getting the following issue.

Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and electron@1.8.4 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: msbuild failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack at emitTwo (events.js:126:13)
gyp ERR! stack at ChildProcess.emit (events.js:214:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--module=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd E:\HelloWorld\electron-quick-start\node_modules\sqlite3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64 --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack at ChildProcess. (E:\HelloWorld\electron-quick-start\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "E:\HelloWorld\electron-quick-start\node_modules\sqlite3\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\HelloWorld\electron-quick-start\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.0 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\NexGen43\AppData\Roaming\npm-cache_logs\2018-03-22T15_44_58_069Z-debug.log

at ChildProcess.childProcess.once.code (E:\HelloWorld\electron-quick-start\node_modules\builder-util\src\util.ts:252:14)
at Object.onceWrapper (events.js:317:30)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Socket.stream.socket.on (internal/child_process.js:346:11)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
at rebuild (E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
at E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
at Generator.next ()
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
at installOrRebuild (E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
at E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\install-app-deps.ts:58:42
at Generator.next ()
From previous event:
at installAppDeps (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\out\cli\install-app-deps.js:51:21)
at then (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:48:33)
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
at Object.args [as handler] (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:48:33)
at Object.runCommand (E:\HelloWorld\electron-quick-start\node_modules\yargs\lib\command.js:235:44)
at Object.parseArgs [as _parseArgs] (E:\HelloWorld\electron-quick-start\node_modules\yargs\yargs.js:1014:30)
at Object.get [as argv] (E:\HelloWorld\electron-quick-start\node_modules\yargs\yargs.js:957:21)
at Object. (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:42:15)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Function.Module.runMain (module.js:684:10)
at startup (bootstrap_node.js:187:16)
at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 postinstall: electron-builder install-app-deps

**Comment by felixrieseberg** [comment]
Please install the build tools globally, not as a dependency:

```
npm install --global --production windows-build-tools
```

**Comment by Saikartik19** [comment]
I did it globally but still facing this issue.

Thanks,
KARTIK

**Comment by jacobq** [comment]
@Saikartik19 if I understand you correctly, you have created a new project based on [`electron-quick-start`](https://github.com/electron/electron-quick-start), added a native dependency (e.g. `sqlite3`), and tried to rebuild it, but the rebuild step fails. To reproduce your problem I created a fork of that same project and used your `package.json` data, see [the repo here](https://github.com/jacobq/electron-quick-start/tree/sqlite3-test). If you clone it and run `npm install` you may see an error like: "Please restart this script from an administrative PowerShell!" because the [`package.json` still lists `windows-build-tools`](https://github.com/jacobq/electron-quick-start/blob/a4e195612ca748a4ed7075b481f39845ebb26c5f/package.json#L35). As [Felix said](https://github.com/felixrieseberg/windows-build-tools/issues/101#issuecomment-375372875), you need to install the package globally, not as a dependency in the project, so you need to remove that line from your package.json file.

**Comment by Saikartik19** [comment]
I downloaded the repo what you created. I tried npm install then I got this error. I'm completely new to node js and electron js So, Please bare me. 

Here is my `package.json`:<summary><details>

```json
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "postinstall": "electron-builder install-app-deps"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "~1.8.2",
    "electron-builder": "^20.5.1",
    "electron-rebuild": "^1.7.3"
  },
  "dependencies": {
    "build": "^0.1.4",
    "clean": "^4.0.2",
    "jquery": "^3.3.1",
    "node-gyp": "^3.6.2",
    "portscanner": "^2.1.1",
    "save": "^2.3.2",
    "sqlite3": "^4.0.0",
    "uuid": "^3.2.1",
    "websocket": "^1.0.25"
  }
}

```
</details>
</summary>

<br>
On npm install I'm getting the following issue:<summary><details>

```
E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds
tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the Proje
ct menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using the v140 bu
ild tools. [E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\websocket\build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds
tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the Proje
ct menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using the v140 bu
ild tools. [E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\websocket\build\validation.vcxproj]

> electron@1.8.4 postinstall E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\electron
> node install.js


> electron-quick-start@1.0.0 postinstall E:\Fixed issue\electron-quick-start-sqlite3-test
> electron-builder install-app-deps

  • electron-builder version=20.6.2
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and electron@1.8.4 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\NexGen43\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\Fixed issue\\electron-quick-start-sqlite3-test\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\Fixed issue\\electron-quick-start-sqlite3-test\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\sqlite3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64 --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Fixed issue\\electron-quick-start-sqlite3-test\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NexGen43\AppData\Roaming\npm-cache\_logs\2018-03-23T06_55_07_035Z-debug.log

    at ChildProcess.childProcess.once.code (E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\builder-util\src\util.ts:252:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\electron-builder\src\cli\cli.ts:48:50)
    at Object.runCommand (E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\yargs\yargs.js:1014:30)
    at Object.get [as argv] (E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (E:\Fixed issue\electron-quick-start-sqlite3-test\node_modules\electron-builder\out\cli\cli.js:148:373)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NexGen43\AppData\Roaming\npm-cache\_logs\2018-03-23T06_55_07_311Z-debug.log
```

</details>
</summary>

**Comment by jacobq** [comment]
@Saikartik19 I just configured a (free for open source projects) Windows CI environment on [AppVeyor](appveyor.com) for this project, and it builds fine ([see the output here](https://ci.appveyor.com/project/jacobq/electron-quick-start/build/1.0.2)). This suggests to me that there is something wrong with your system / build environment. If I were in your place I would try to uninstall (via add/remove programs) the software installed by `windows-build-tools` (unfortunately, running `npm remove windows-build-tools` does not do this yet) manually then reinstall, taking care to follow all of the instructions (e.g. using admin/elevated powershell to launch, etc.). If you have manually installed software like MS Visual Studio or made other changes to your system that might affect the software used by node (i.e. by `node-gyp`) to compile native modules then that may be causing the problem. Also, if you want to see more debugging output, you can try setting the `DEBUG` environment variable, e.g. run `DEBUG=* npm run postinstall`.
