### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by kbsachin01** [felixrieseberg/windows-build-tools#109]
Downloading BuildTools_Full.exe
Error: unable to get local issuer certificate
{ Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
+ windows-build-tools@2.2.1
updated 1 package in 23.269s

**Comment by flotwig** [comment]
I'm having the same issue. Even though `--strict-ssl` is not set, I can't do it. It appears this line is not doing what we think it is:

https://github.com/felixrieseberg/windows-build-tools/blob/eee4a9b7c7c4eeccfd7c2135ab2e76ea7581021c/src/download.ts#L35

**Comment by jacobq** [comment]
Hmm, it looks to me like we're using it correctly. To disable strict mode the [README says](https://github.com/maxogden/nugget/blob/v2.0.1/readme.md#options) to pass the `--no-strict-ssl` argument to the command-line version, which it [interprets](https://github.com/maxogden/nugget/blob/2932a1852ff0f3c1306080d969e6b41266d007dd/bin.js#L23) through [`minimist`](https://github.com/substack/minimist) as `opts.strictSSL = args['strict-ssl'] = false;` and then [calls `nugget` with those `opts`](https://github.com/maxogden/nugget/blob/v2.0.1/bin.js#L26).

**Comment by flotwig** [comment]
Yeah, it turned out that I had never set `strict-ssl` on npm - I've been using `yarn` exclusively on this PC. Kinda embarrassing. 😊 Once I did `npm set strict-ssl false`, it worked as intended!

**Comment by jacobq** [comment]
@flotwig Glad to hear it. You may want to consider setting that in a [global `npmrc` file](https://docs.npmjs.com/files/npmrc).

@kbsachin01 I believe this solution will work for you as well. If not, please comment with more details and we'll reopen the issue.
