### ISSUE TITLE
can it support the cmake-js?

### ISSUE THREAD

**Issue by whtiehack** [felixrieseberg/windows-build-tools#111]
![image](https://user-images.githubusercontent.com/12741016/39507366-2f54d590-4e10-11e8-97e2-74d04b151c40.png)
thx.

**Comment by jacobq** [comment]
This package just installs the tools. It doesn't control which tools are compatible / needed. As far as I know, Microsoft's C++ compilers are the only ones that work with NodeJS (e.g. [`node-gyp`](https://github.com/nodejs/node-gyp/issues/802)) on Windows. You can see hints of this in the documentation, e.g. ["This will generate either a Makefile (on Unix platforms) or a **vcxproj** file (on Windows) in the build/ directory."](https://nodejs.org/api/addons.html#addons_building)

**Comment by jacobq** [comment]
Maybe I misunderstood your question. If you are trying to install the VS build tools / C++ compiler to be able to use some other tool that should be fine. If you just need that one package though you could instead just [install it directly](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/introducing-the-visual-studio-build-tools/) (["Download	
Build Tools for Visual Studio 2017" link near the bottom](https://www.visualstudio.com/downloads/)).

**Comment by whtiehack** [comment]
thanks for answer, maybe my question not clear, sorry. 
i think the problem is the cmake-js's detect.
https://github.com/cmake-js/cmake-js/blob/3456bb8177137738c2ae1d6484945efe680a5031/lib/es6/vsDetect.js#L22
