### ISSUE TITLE
Error: Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by trophyDev** [felixrieseberg/windows-build-tools#112]
I am trying to install an authoring_tool and I am getting this error when I run 'node install' after following this tutorial [https://github.com/adaptlearning/adapt_authoring/wiki/Developer's-Install](https://github.com/adaptlearning/adapt_authoring/wiki/Developer's-Install)
![capture](https://user-images.githubusercontent.com/9076394/39566169-f3c2f56a-4eba-11e8-9070-d67c5b979099.PNG)

**Comment by jacobq** [comment]
I don't understand what this has to do with `windows-build-tools`. Perhaps you should contact the author of that project? (adapt.learning@kineo.com)
