### ISSUE TITLE
 Unexpected end of JSON input while parsing near '...uid":"~1.4.0","qs":"~'

### ISSUE THREAD

**Issue by vidries** [felixrieseberg/windows-build-tools#114]
can you help me?
when i run : npm install --global --production windows-build-tools,
the error as follow,
Unexpected end of JSON input while parsing near '...uid":"~1.4.0","qs":"~'

**Comment by jacobq** [comment]
It sounds like you have a syntax error in your `package.json` file. Try checking it with a tool like [package-json-validator.com](http://package-json-validator.com/). I am pretty sure this is unrelated to `windows-build-tools`.
