### ISSUE TITLE
Build Tools finish installation, but installer does not exit

### ISSUE THREAD

**Issue by 7NT** [felixrieseberg/windows-build-tools#116]
node --version: v10.2.1
npm --version: 6.1.0

command:
npm --add-python-to-path='true' --debug install --global windows-build-tools
![python](https://user-images.githubusercontent.com/4128389/40596910-e7955774-61f2-11e8-877f-f85bd19725d8.png)

never get it installed, it hangs there for hours

**Comment by bferdinandus** [comment]
I experience the same problem.
Windows 10 (1803) 
Node v8.11.2
Npm v6.1.0

![image](https://user-images.githubusercontent.com/4364969/40604233-bf47dc26-625e-11e8-97f3-f82d08d26eec.png)

this process doesn't seem to finish:
![image](https://user-images.githubusercontent.com/4364969/40604311-ec66c8fc-625e-11e8-9d93-32d13649b047.png)

**Comment by lefrancois** [comment]
Same here… :(

**Comment by felixrieseberg** [comment]
Thanks for the report! Interestingly enough, it appears that installation did succeed, the process is just not exiting 🤔

**Comment by alexdevero** [comment]
I have the same issue with updating from 2.3.0 to 3.0.0:
```
$ npm -g i windows-build-tools@latest                                                      
                                                                                           
> windows-build-tools@3.0.0 postinstall C:\Users\AppData\Roaming\npm\node_modules\wind
ws-build-tools                                                                             
> node ./dist/index.js                                                                     
                                                                                           
Downloading BuildTools_Full.exe                                                            
[>                                            ] 0.0% (0 B/s)                               
Downloaded BuildTools_Full.exe. Saved to C:\Users\.windows-build-tools\BuildTools_Full
exe.                                                                                       
                                                                                           
Starting installation...                                                                   
Launched installers, now waiting for them to finish.                                       
This will likely take some time - please be patient!                                       
                                                                                           
Status from the installers:                                                                
---------- Visual Studio Build Tools ----------                                            
[0288:0CE8][2018-05-30T10:52:47]i371: Updating session, registration key: SOFTWARE\Microsof
\Windows\CurrentVersion\Uninstall\{a9528995-e130-4501-ae19-bbfaddb779cc}, resume: ARP, rest
rt initiated: No, disable resume: No                                                       
[08D8:1584][2018-05-30T10:52:47]i399: Apply complete, result: 0x0, restart: None, ba reques
ed restart:  No                                                                            
                                                                                           
------------------- Python --------------------                                            
Python 2.7.14 is already installed, not installing again.                                  
```

**Comment by bferdinandus** [comment]
I managed to get the "npm i -g windows-build-tools" to finish correctly. 

At the point where the Visual Studio Build tools showed this: "[B6A4:BCB0][2018-05-30T11:32:46]i399: Apply complete, result: 0x0, restart: None, ba requested restart:  No" 
Then I started the taskmanager to kill the "BuildTools_Full.exe"
Then I added the following to the "build-tools-log.txt" : Variable: IsInstalled = 1

then the npm install of windows build tools finished with success.

Hope this helps.

**Comment by Philam18** [comment]
@bferdinandus solution worked for me.
When the installer has reached the point:
```
---------- Visual Studio Build Tools ----------
[1918:0CCC][2018-05-30T17:47:07]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{a9528995-e130-4501-ae19-bbfaddb779cc}, resume: ARP, restart initiated: No, disable resume: No
[0338:0FB8][2018-05-30T17:47:07]i399: Apply complete, result: 0x0, restart: None, ba requested restart:  No

------------------- Python --------------------
Python 2.7.15 is already installed, not installing again.
```
1, Open task manager and kill the `BuildTolls_Full.exe` process
2. Go to `C:\Users\<User Name>\.windows-build-tools` and open `build-tools-log.txt` with a text-editor
3. Append the following:
```
Variable: IsInstalled = 1
``` 
4. Save it, and back at the console, npm should have finished.

**Comment by AGFlash** [comment]
@phil'n'bfer: good spot

**Comment by phil** [comment]
Surely credit should go to @Philam18 and @bferdinandus  #usernamefail

**Comment by aliaksandr-adzinets** [comment]
There is no "BuildTools" (or BuildTolls") in my "Processes" and "Details". 
So for me it still hangs without a solution @ Node.js 10.15, npm 6.5, Win10.

```
PS C:\Windows\system32> npm install --global --production windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

Downloading python-2.7.15.amd64.msi
[============================================>] 100.0% of 20.25 MB (417.45 kB/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\user\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[============================================>] 100.0% of 1.12 MB (746.57 kB/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\user\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
2019-01-02T02:08:08 : Verbose : Spawning uninstall stub
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Stream was closed
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Stream was closed
------------------- Python --------------------
Successfully installed Python 2.7
```

**Comment by aliaksandr-adzinets** [comment]
There is no "BuildTools" (or BuildTolls") in my "Processes" and "Details". 
There's also no build-tools-log.txt file, only vs_BuildTools.exe and some files for Python's installer.
So for me it still hangs without a solution @ Node.js 10.15, npm 6.5, Win10.

```
PS C:\Windows\system32> npm install --global --production windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

Downloading python-2.7.15.amd64.msi
[============================================>] 100.0% of 20.25 MB (417.45 kB/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\user\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[============================================>] 100.0% of 1.12 MB (746.57 kB/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\user\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
2019-01-02T02:08:08 : Verbose : Spawning uninstall stub
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Stream was closed
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Stream was closed
------------------- Python --------------------
Successfully installed Python 2.7
```

**Comment by aliaksandr-adzinets** [comment]
I also thought it's kind of a bug that installing windows-build-tools hung at the following step:

```
PS C:\Windows\system32> npm install --global --production windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

Downloading python-2.7.15.amd64.msi
[============================================>] 100.0% of 20.25 MB (417.45 kB/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\user\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[============================================>] 100.0% of 1.12 MB (746.57 kB/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\user\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
2019-01-02T02:08:08 : Verbose : Spawning uninstall stub
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Stream was closed
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Stream was closed
------------------- Python --------------------
Successfully installed Python 2.7
```

However, later I realized that vs_installerservice.exe was just downloading a big chunk of data in the background. It's not okay to have such a behavior for someone whose Internet connection is limited or metered. I think a fix is required.

**Comment by aliaksandr-adzinets** [comment]
I also thought it's kind of a bug that installing windows-build-tools hung at the following step:

```
PS C:\Windows\system32> npm install --global --production windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

Downloading python-2.7.15.amd64.msi
[============================================>] 100.0% of 20.25 MB (417.45 kB/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\user\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[============================================>] 100.0% of 1.12 MB (746.57 kB/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\user\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
2019-01-02T02:08:08 : Verbose : Spawning uninstall stub
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Stream was closed
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Stream was closed
------------------- Python --------------------
Successfully installed Python 2.7
```

However, later I realized that vs_installerservice.exe was downloading a big chunk of data in the background. (I used Windows Resource Manager to find it out.) It's not okay to have such a behavior for someone whose Internet connection is limited or metered. Moreover, even after the downloading finished, nothing happened anymore, so the installation process kept hanging.

**Comment by aliaksandr-adzinets** [comment]
I also thought it's kind of a bug that installing windows-build-tools hung at the following step:

```
PS C:\Windows\system32> npm install --global --production windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

Downloading python-2.7.15.amd64.msi
[============================================>] 100.0% of 20.25 MB (417.45 kB/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\user\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[============================================>] 100.0% of 1.12 MB (746.57 kB/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\user\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
2019-01-02T02:08:08 : Verbose : Spawning uninstall stub
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [InstallerImpl]: Stream was closed
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2019-01-02T02:08:08 : Verbose : [SetupUpdaterImpl]: Stream was closed
------------------- Python --------------------
Successfully installed Python 2.7
```

However, later I realized that vs_installerservice.exe was downloading a big chunk of data in the background. (I used Windows Resource Manager to find it out.) It's not okay to have such a behavior for someone whose Internet connection is limited or metered. Moreover, even after the downloading finished, nothing happened anymore, so the installation process kept hanging.

I'm on Windows 10 (build 1607), 
```
$ npm version
{ npm: '6.5.0',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.0',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.45',
  zlib: '1.2.11' }
```

**Comment by lost-vetern** [comment]
first try this one.. 
`npm install --global --production --verbose windows-build-tools`
then u can use your normal command.
worked for me

**Comment by arunraj2017** [comment]
My system also got hang on the same place 'Successfully installed Python 2.7',  I gave ^C to end the task and the process is not running again! Seems like it ran into some infinite loop and when I tried to cancel, the loop ended and continued with rest of the process.
===========================================

---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Successfully installed Python 2.7

Now configuring the Visual Studio Build Tools and Python...

All done!

**Comment by hahaha33333222** [comment]
> first try this one..
> `npm install --global --production --verbose windows-build-tools`
> then u can use your normal command.
> worked for me

this actually worked for me, I've been looking for 2 DAYS! thnx so much for the help <3

**Comment by NoobCoding94** [comment]
> @bferdinandus solution worked for me.
> When the installer has reached the point:
> 
> ```
> ---------- Visual Studio Build Tools ----------
> [1918:0CCC][2018-05-30T17:47:07]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{a9528995-e130-4501-ae19-bbfaddb779cc}, resume: ARP, restart initiated: No, disable resume: No
> [0338:0FB8][2018-05-30T17:47:07]i399: Apply complete, result: 0x0, restart: None, ba requested restart:  No
> 
> ------------------- Python --------------------
> Python 2.7.15 is already installed, not installing again.
> ```
> 
> 1, Open task manager and kill the `BuildTolls_Full.exe` process
> 2. Go to `C:\Users\<User Name>\.windows-build-tools` and open `build-tools-log.txt` with a text-editor
> 3. Append the following:
> 
> ```
> Variable: IsInstalled = 1
> ```
> 
> 1. Save it, and back at the console, npm should have finished.

This solution work for me. Thanks.

**Comment by basickarl** [comment]
This is still affecting certain people (me). Does anyone know what is happening?

**Comment by HermitSun** [comment]
> first try this one..
> `npm install --global --production --verbose windows-build-tools`
> then u can use your normal command.
> worked for me

thank you! you saved my day!

**Comment by chitraanshpopli** [comment]
For those who are still stuck. Try this: https://github.com/felixrieseberg/windows-build-tools/issues/172#issuecomment-484091133

It solved mine. And of many others :)

**Comment by fabiovaz** [comment]
npm config set msvs_version 2017

**Comment by u10k** [comment]
npm install --global --production --verbose windows-build-tools

is does`t work
![image](https://user-images.githubusercontent.com/22042799/128707434-e2dca02e-087d-4311-89a3-6831983bfdfb.png)

**Comment by yunnysunny** [comment]
> @bferdinandus solution worked for me.
> When the installer has reached the point:
> 
> ```
> ---------- Visual Studio Build Tools ----------
> [1918:0CCC][2018-05-30T17:47:07]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{a9528995-e130-4501-ae19-bbfaddb779cc}, resume: ARP, restart initiated: No, disable resume: No
> [0338:0FB8][2018-05-30T17:47:07]i399: Apply complete, result: 0x0, restart: None, ba requested restart:  No
> 
> ------------------- Python --------------------
> Python 2.7.15 is already installed, not installing again.
> ```
> 
> 1, Open task manager and kill the `BuildTolls_Full.exe` process
> 2. Go to `C:\Users\<User Name>\.windows-build-tools` and open `build-tools-log.txt` with a text-editor
> 3. Append the following:
> 
> ```
> Variable: IsInstalled = 1
> ```
> 
> 1. Save it, and back at the console, npm should have finished.

I don't have `build-tools-log.txt` in  `C:\Users\<User Name>\.windows-build-tools` :
```powershell
PS C:\Users\yunny\.windows-build-tools> dir


    目录: C:\Users\yunny\.windows-build-tools


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2021/8/10     12:32                python27
-a----         2021/8/10     12:30       20246528 python-2.7.15.amd64.msi
-a----         2021/8/10     13:03          51740 python-log.txt
-a----         2021/8/10     12:30        1119848 vs_BuildTools.exe
```
But I still hang after install python 2.7:

```
> windows-build-tools@5.2.2 postinstall D:\npm\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\yunny\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\yunny\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Still waiting for installer log file...
------------------- Python --------------------
Successfully installed Python 2.7
```

**Comment by amzbiz** [comment]
I've tried all of this and none of it works. Essentially there doesn't seem to be any way to install windows-build-tools on Node 12. Which means I can't get SASS working due to the errors it's getting. Linux here I come.
