### ISSUE TITLE
no project data build/binding.sln

### ISSUE THREAD

**Issue by brandNewUser666** [felixrieseberg/windows-build-tools#120]
Hi guys, 

i do have the following problem for days, without getting it solved. I would like to install noble cause ob BLE access; but as soon as it comes to installing windows-build-tools i run into trouble. 
Finally I installed Python 2.7 and wbtools by my own and made the configurations (npm config set msvs_version 2015) as written in the readme manual. But when I start to go one step further (installing noble, i do already have the node-gyp (compiler) (I already reinstalled vs2017 and the redistributables 2015 (64bit and 32bit) twice) ) i get the following all the time. I do 

``C:\WINDOWS\system32\node_modules\bluetooth-hci-socket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
MSBUILD : error MSB1009: Die Projektdatei ist nicht vorhanden.
Schalter: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\bluetooth-hci-socket
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN saveError ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules\bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ noble@1.9.1
updated 1 package in 7.723s

C:\WINDOWS\system32>``

Is there somebody to help me?

**Comment by felixrieseberg** [comment]
Hm, this appears to be more an issue with the project / MSBuild / your computer configuration than `windows-build-tools`. It _may_ have something to do with installing Visual Studio 2017 before installing `windows-build-tools` – I know from personal experience that installing any version of VS2015 after installing any version of VS2017 can mess things up. I know, it's sad.
