### ISSUE TITLE
npm install --global --production windows-build-tools stcuk on All done!

### ISSUE THREAD

**Issue by raymondhani** [felixrieseberg/windows-build-tools#129]
i was using this command 
npm install --global --production windows-build-tools

and it installed everything but then stuck on all done! 

does this means that the installation is over ?

i am using normal cmd in administrative run.

i cannot run any other commands  without pressing ctrl+c to stop the current command

![capture](https://user-images.githubusercontent.com/33130052/41846387-cd73b5da-7876-11e8-887f-85cdd5987c7d.PNG)

**Comment by spnraju** [comment]
I am also facing the same scenario. Is this how it is completed? or we need to wait for some more time?

**Comment by raymondhani** [comment]
I've waited way too long and it finished ...don't close it wait more time ..

**Comment by spnraju** [comment]
@raymondhani just curious to know how much time it took. Hours? Minutes?

**Comment by arueckauer** [comment]
Having the same issue here. @raymondhani How long did it take in your case? It has been running for 4.5 hours and it's still not done.

**Comment by utaylsa1** [comment]
Running this command using cygwin and when I highlight the bottom line it scrolls up so I suspect it is still downloading.
![Untitled](https://user-images.githubusercontent.com/48446562/54135219-c9005e00-43ef-11e9-99ea-bef45d025b70.png)
