### ISSUE TITLE
Cannot find VS2017 installer log file

### ISSUE THREAD

**Issue by REEMERGEMEDIA** [felixrieseberg/windows-build-tools#130]
I installed VS2015 using the latest version of windows-build-tools. I'm now trying to install VS2017 and installation always hangs on 

> Visual Studio Build Tools: Still waiting for installer log file...

I've tried using version 2.1.5 of WBT, Python installs but still no dice with VS2017.

@felixrieseberg Do you have any insight here? If you need more information, please let me know.

Thanks!

**Comment by liuliangsir** [comment]
Same issue here.
Here are a couple of screenshots.

![image](https://user-images.githubusercontent.com/8049878/42322781-4709b50e-8090-11e8-9672-795cc309f2e9.png)

**Comment by REEMERGEMEDIA** [comment]
It's possible it could have been issues with my corporate laptop. I ended up using a VM and the steps I documented here. https://stackoverflow.com/questions/47248153/build-sqlite3-with-electron-is-not-working/51107560#51107560

**Comment by felixrieseberg** [comment]
Sorry to hear that! Visual Studio's installer's log files are a bit cryptic - we're expecting them in `%TEMP%\` and to begin with `dd_client_`. If you got a minute, I'd love to know if they're not present for you - and if not, if they're in some mystical other place 😅

**Comment by thasmo** [comment]
I installed VS2017 build tools prior and `windows-build-tools` would hang with `Visual Studio Build Tools: Still waiting for installer log file...`. I had to uninstall the VS2017 build tools manually first and afterwards it would not hang anymore.

**Comment by thasmo** [comment]
After a fourth or fifth run it actually worked now. Not sure if it actually influenced anything, but I manually started `vs_BuildTools.exe` once, actually cancelled it, and then ran `npm --vs2017 install --global --production windows-build-tools` again.

**Comment by jordanbtucker** [comment]
See #135

**Comment by thasmo** [comment]
@jordanbtucker Thanks for investigating, reporting and letting me know. 👍

**Comment by felixrieseberg** [comment]
Thank you all, this _should_ be fixed in 385951730893ea7adec98241ec778b95e487a85c.
