### ISSUE TITLE
Process never get finished

### ISSUE THREAD

**Issue by dattajadhav44** [felixrieseberg/windows-build-tools#131]
![screenshot_2](https://user-images.githubusercontent.com/40449078/42132171-75f56240-7d30-11e8-8be9-903fafc3a294.png)

npm --add-python-to-path='true' --debug install --global windows-build-tools
i am trying to install the windows build tool but not getting succeed. Can someone please help on this

**Comment by liuliangsir** [comment]
Same issue here.
Here are a couple of screenshots.

![image](https://user-images.githubusercontent.com/8049878/42322781-4709b50e-8090-11e8-9672-795cc309f2e9.png)

**Comment by felixrieseberg** [comment]
Thank you for the report! This is now fixed. It's a bit scary that the Visual Studio Build Tools installer doesn't exit on its own, but we at least exit the `npm install` process when we detected that we're all done.
