### ISSUE TITLE
Gets stuck on "all done"

### ISSUE THREAD

**Issue by danielntech** [felixrieseberg/windows-build-tools#132]
![image](https://user-images.githubusercontent.com/16944217/43001407-cd46c37a-8c2d-11e8-9652-7249679d062b.png)

Instead of adding the package it says all done and gets stuck.

**Comment by felixrieseberg** [comment]
This is now fixed. It's a bit scary that the Visual Studio Build Tools installer doesn't exit on its own, but we at least exit the `npm install` process when we detected that we're all done.
