### ISSUE TITLE
Yarn needs Python to be in $PATH

### ISSUE THREAD

**Issue by paulcbetts** [felixrieseberg/windows-build-tools#134]
Installing windows-build-tools won't make Yarn be able to build native modules, it still finds out that `python` isn't in $PATH and gets grump about it

**Comment by felixrieseberg** [comment]
Do you think we should turn `--add-python-to-path` on by default? We’ve stopped installing it if we can find Python, so we might actually be able to now do so without breaking too many people :thinking_face:

**Comment by paulcbetts** [comment]
@felixrieseberg I am Into™ this idea, you can't be any worse than the nVidia driver that dumps like 4+ items onto PATH

**Comment by justinmeiners** [comment]
Same issue here.

**Comment by felixrieseberg** [comment]
I'm convinced, fixed in 7f19d651a32b04732d3eaccbd88cf7ddfb51d0da.
