### ISSUE TITLE
Admin check does not work properly in Powershell 6.1 preview 4

### ISSUE THREAD

**Issue by mikemaccana** [felixrieseberg/windows-build-tools#136]
Using Powershell 6.1 preview 4, the command fails the admin check - even though it's being run as administrator:

![image](https://user-images.githubusercontent.com/172594/44028496-faba9b52-9ef1-11e8-9aaa-38ed5047941e.png)

Running the same command in Powershell 5 admin works fine. Not a big deal but worth updating the admin check for newer Powershells.

**Comment by felixrieseberg** [comment]
Hey @mikemaccana, I just downloaded the PowerShell 6.1 RC1 and couldn't reproduce the issue anymore. I hope this is fixed!
