### ISSUE TITLE
Is it free for commercial (enterprise) use?

### ISSUE THREAD

**Issue by Den-dp** [felixrieseberg/windows-build-tools#15]
As I understand, this package (set of tools) is free for open source and non-commercial use.

Can you elaborate more on *is it free for commercial (enterprise) use*?

Any links will be appreciated.
Thanks

**Comment by felixrieseberg** [comment]
Hey, the build tools are a standalone product - you can [find the license here](https://www.visualstudio.com/en-us/support/legal/mt644918). I am not a lawyer and not in any position to give you legal advice (annoying, I know), but my personal, non-lawyer answer is "yes" 😉 .
