### ISSUE TITLE
_removeReaction and MessageReactionRemove

### ISSUE THREAD

**Issue by harmdhast** [felixrieseberg/windows-build-tools#151]
When removing a reaction from an old message (cached with fetchMessage), 
the MessageReactionRemove event is not triggered.
This because, _removeReaction does not return the reaction object as it does not find the user id in the removedReaction.
I don't know if its an intended behavior. However, this causes problems when trying to get events fired on older uncached messages.
I fixed it without problems by moving the return statement in the _removeReaction outside of the userid condition. While keeping the null return if the reaction in not found.

I did not submit a PR as I don't know if it is an indented behavior.
Thanks :)

**Comment by harmdhast** [comment]
Wrong fucking browser tab
Gonna kms

**Comment by jacobq** [comment]
No worries -- it happens :)
