### ISSUE TITLE
Can't Install Windows Build Tools

### ISSUE THREAD

**Issue by bwhybrow23** [felixrieseberg/windows-build-tools#164]
I am trying to install Quick.db, a NPM package for Discord.JS and to install it I need Windows Build Tools. 

I tried installing Windows Build Tools using `npm -g --add-python-to-path --vs2017 install windows-build-tools node-gyp` and I got this error https://pastebin.com/Q9FZrS0G 

I thought then maybe it had been successful because at the bottom it read 
`+ node-gyp@3.8.0
+ windows-build-tools@5.0.0
updated 2 packages in 173.711s`

I then went to install quick.db `npm i quick.db` and it gave me this error https://pastebin.com/DwfDNNyY . This is what is in the log file [2018-12-15T10_14_21_701Z-debug.log](https://github.com/felixrieseberg/windows-build-tools/files/2682541/2018-12-15T10_14_21_701Z-debug.log)

I've asked around with some fellow developers and the creators of quick.db and none of them know what is the issue. 

Thanks in advance!

**Comment by Sun1ive** [comment]
+1 same here

**Comment by Tonysmark** [comment]
I just got same problem
```bash
```

**Comment by PanelGrid** [comment]
Same here, my python installer is there, in the offline-installers path given, but it could not find it. WhY?
