### ISSUE TITLE
Is a portable installation possible?

### ISSUE THREAD

**Issue by cyberpunkbln** [felixrieseberg/windows-build-tools#173]
Hello,
short question. Is a portable installation possible?

Or is it so easy that i set all enviroments to my portable node.js installation and what envs i need?

thx

**Comment by refack** [comment]
From my experience the short answer is no.
Most parts _could_ be made portable, except for the Windows SDK. It requires some registry keys:
```
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots\10.0.17134.0
```
The environment vars required are `Path` and whatever `vcvarsall.bat` sets. I store those with `set > devenv.txt` and then run `FOR /F "tokens=*" %i in (devenv.txt) do set %i` in the cmd session I want to use

**Comment by cyberpunkbln** [comment]
thx good to know;), i hope that the projects that use can use an gnu-ming-env, then;).
