### ISSUE TITLE
 win10 ver17763.316   Could not install Visual Studio Build Tools.

### ISSUE THREAD

**Issue by Archer456** [felixrieseberg/windows-build-tools#175]
My windows10   winver is 1809    os version is  17763.316 

this is 5.1.0 

PS C:\WINDOWS\system32> npm install --global windows-build-tools

> windows-build-tools@5.1.0 postinstall D:\nodejs\node-global\node_modules\windows-build-tools
> node ./dist/index.js

Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\cmd\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
2019-02-14T11:06:21 : Verbose : [InstalledProductsProviderImpl]: Stream was closed
2019-02-14T11:06:21 : Verbose : [InstallerImpl]: Rpc connection was closed.
2019-02-14T11:06:21 : Verbose : [InstallerImpl]: Stream was closed
2019-02-14T11:06:21 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2019-02-14T11:06:21 : Verbose : [SetupUpdaterImpl]: Stream was closed
------------------- Python --------------------
Python 2.7.14 is already installed, not installing again.

Could not install Visual Studio Build Tools.
Please find more details in the log files, which can be found at
C:\Users\cmd\.windows-build-tools

Skipping configuration: No configuration for Python or Visual Studio Build Tools required.
TypeError: Cannot read property 'then' of undefined
    at install_1.install (D:\nodejs\node-global\node_modules\windows-build-tools\dist\start.js:19:17)
    at launch_1.launchInstaller.then.then.then (D:\nodejs\node-global\node_modules\windows-build-tools\dist\install\index.js:34:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
+ windows-build-tools@5.1.0
updated 1 package in 24.535s

this is 5.0.0  
PS C:\WINDOWS\system32> npm install --global windows-build-tools@5.0.0

> windows-build-tools@5.0.0 postinstall D:\nodejs\node-global\node_modules\windows-build-tools
> node ./dist/index.js

Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\cmd\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
2019-02-14T11:08:16 : Verbose : [InstalledProductsProviderImpl]: Stream was closed
2019-02-14T11:08:16 : Verbose : [InstallerImpl]: Rpc connection was closed.
2019-02-14T11:08:16 : Verbose : [InstallerImpl]: Stream was closed
2019-02-14T11:08:16 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2019-02-14T11:08:16 : Verbose : [SetupUpdaterImpl]: Stream was closed
------------------- Python --------------------
Python 2.7.14 is already installed, not installing again.

Could not install Visual Studio Build Tools.
Please find more details in the log files, which can be found at
C:\Users\cmd\.windows-build-tools

Skipping configuration: No configuration for Python or Visual Studio Build Tools required.
TypeError: Cannot read property 'then' of undefined
    at install_1.install (D:\nodejs\node-global\node_modules\windows-build-tools\dist\start.js:19:17)
    at launch_1.launchInstaller.then.then.then (D:\nodejs\node-global\node_modules\windows-build-tools\dist\install\index.js:34:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
+ windows-build-tools@5.0.0
removed 1 package and updated 5 packages in 16.211s

**Comment by Archer456** [comment]
4.0.0  is ok

PS C:\WINDOWS\system32> npm install --global --production windows-build-tools@4.0.0

> windows-build-tools@4.0.0 postinstall D:\nodejs\node-global\node_modules\windows-build-tools
> node ./dist/index.js



Downloading BuildTools_Full.exe
[============================================>] 100.0% of 3.29 MB (3.29 MB/s)
Downloaded BuildTools_Full.exe. Saved to C:\Users\cmd\.windows-build-tools\BuildTools_Full.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.14 is already installed, not installing again.

Now configuring the Visual Studio Build Tools..

All done!

+ windows-build-tools@4.0.0
updated 1 package in 94.299s

**Comment by ArghyaRoyC** [comment]
I am also facing the same issue.

**Comment by blowsie** [comment]
Same 4.0.0 also works for me

**Comment by dr3x** [comment]
Same issue for me, may be this line in start.js:

`            environment_1.setEnvironment(variables)
                .then(() => process.exit(0))`

**Comment by jacobq** [comment]
> may be this line in start.js:

That's part of the machine translated / compiled output that corresponds with:

https://github.com/felixrieseberg/windows-build-tools/blob/f2a146fde966cfac46e4bce75ea31d291821b938/src/start.ts#L15-L26

And the call to `setEnvironment` uses the following code to launch [`set-environment.ps1`](https://github.com/felixrieseberg/windows-build-tools/blob/e02b4ba426c343424728feecb10902f2d6946e25/ps1/set-environment.ps1): 

https://github.com/felixrieseberg/windows-build-tools/blob/e02b4ba426c343424728feecb10902f2d6946e25/src/environment.ts#L55-L57

JavaScript allows whitespace around the [`.` (property accessor)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors), so `somePromise  .then(...)` is equivalent to `somePromise.then(...)`. Is there something else about the above code that looks wrong?
