### ISSUE TITLE
Removed everything related to windows-build-tools, removed from PATH and node still seeing it - how to remove windows-build-tools completely?

### ISSUE THREAD

**Issue by randompassanger** [felixrieseberg/windows-build-tools#184]
Hello,
I tried windows-build-tools but it was not working and also it broke something in my Node.js installation. When trying 

    npm install

in directory of project, it says
```
gyp verb check python checking for Python executable "C:\Users\Sebastian\.windows-build-tools\python27\python.exe" in the PATH
```
I removed Windows Kits, Visual Studio Installer, Python (also from PATH), removed folder

    .windows-build-tools

and Node still see windows-build-tools. Please help because I'm struggling with it second day.

**Comment by felixrieseberg** [comment]
Your issue is likely related to `npm` still being configured to look for Python in that path. Run this:

```
npm config delete python
```
