### ISSUE TITLE
Node v6 and v7 on Travis

### ISSUE THREAD

**Issue by tugrul** [felixrieseberg/windows-build-tools#189]
I wanted to build & test my addon for node version 6 and 7 on travis.

You can see build status and output logs from this link: https://travis-ci.org/tugrul/cryptian

I tried to get your library on `before_install` to travis test image. But I'm not able to success.

Then I tried install dependencies by classical way.

First I encountered following error.

`MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".`

I was able to solve this issue by helps of MSBuild staff. https://github.com/microsoft/msbuild/issues/4415

Then i encountered second issue. 

```
error MSB3428: Could not load the Visual C++ component "VCBuild.exe". 
To fix this, 
1) install the .NET Framework 2.0 SDK, 
2) install Microsoft Visual Studio 2005 or 
3) add the location of the component to the system path if it is installed elsewhere.
```

But MSBuild staff couldn't help me and he refers to node community.

Also I wrote to travis-ci community but there is no response by staff.

What I should install to solve second issue by your experience?. I tried many build tools package from [Chocolatey](https://chocolatey.org/) but I couldn't succeed. 

It should chocolatey package or silent installer package. Because I don't have direct access to travis image. I'm able to only give directives by config file.

**Comment by felixrieseberg** [comment]
I took a look right now and it doesn't seem like you're using `windows-build-tools` at all. What's the thing you're trying to build?

**Comment by tugrul** [comment]
@felixrieseberg yes this build step not using `windows-build-tools`.

I tried to use before and I couldn't success. You can see log of that build step here. https://travis-ci.org/tugrul/cryptian/jobs/536786024

**Comment by felixrieseberg** [comment]
In this log, it appears that Microsoft's installer hangs with `Updating installer`. That doesn't seem like a bug with this tool but rather Visual Studio. I suggest you report it there!

**Comment by tugrul** [comment]
@felixrieseberg I know this is not bug. I just wanted to get your advise by experience. Should I install visual studio to get dependencies? Is not there a standalone package to get msbuild tool?
