### ISSUE TITLE
node-gyp rebuild :: after installing windows-build-tools

### ISSUE THREAD

**Issue by yabasha** [felixrieseberg/windows-build-tools#19]
I'm facing hard times building my project which uses module `iltorb@1.0.12`. Failed at the iltorb@1.0.12 install script 'node-gyp rebuild', even after installing windows-build-tools: https://github.com/felixrieseberg/windows-build-tools and installing VS2015 do all node-gyp prerequisites but no luck:

nodejs: 6.3.1
npm: 3.10.3
OS: Windows 10

Please advice, I attached npm-debug, if it may help to clarify the problem.

[npm-debug.txt](https://github.com/felixrieseberg/windows-build-tools/files/415487/npm-debug.txt)

Thanx,

**Comment by felixrieseberg** [comment]
Hm, I'm not sure - it's possible that it's not an issue with your machine, but with that package. I tried installing it on my machine and that worked fine. Did you have any luck with any other native addons?

**Comment by yabasha** [comment]
after upgrading node it worked perfectly `npm i -g npm` the new version `3.10.6` it seems that the version `3.10.3` that comes with `node v6.3.1` has a bug, which itself depends on an outdated version of node-gyp. The updated node-gyp fixes the __pfnDliNotifyHook2 error.
https://github.com/nodejs/node-gyp/pull/952

**Comment by felixrieseberg** [comment]
Happy to hear that things worked out for you 😌 ! I'm closing this, but feel free to reopen if I misunderstood you!
