### ISSUE TITLE
Publish 5.2.x to npm

### ISSUE THREAD

**Issue by connor4312** [felixrieseberg/windows-build-tools#190]
A release has been tagged but the latest npm version is 5.1.0. It'd be great if this could be published for the bug fixes it contains.

**Comment by felixrieseberg** [comment]
Hm, it looks like our automatic CI failed here. I'll take a quick look.

**Comment by felixrieseberg** [comment]
And fixed, thanks for bringing that to my attention!

**Comment by connor4312** [comment]
Great, thanks!
