### ISSUE TITLE
Python - still waiting for installer log file

### ISSUE THREAD

**Issue by mythicalbadger** [felixrieseberg/windows-build-tools#192]
Hey, 
I know there are lots of other threads with this issue, but I have read all of them and tried their solutions, and my installation is still not working. It always gets stuck on the Python "Still waiting for installer log file".

I've tried
`npm install -g windows-build-tools`
`npm install -g windows-build-tool@4.0.0`
as well as both with the --production option,
`npm --add-python-to-path='true' --debug install --global windows-build-tools`

I've also tried
- Using different versions of node (8.11.2 and 8.16.0)
- `msiexec /n /lvx+! python-log.txt /i python-2.7.14.amd64.msi /quiet` which made 6kb log file that didn't do anything

It still **always hangs on the Python 'still waiting for installer log file'**. Is there any way I can fix this? I've read through the forums multiple times, and to no avail. I just bought a new computer, but it worked on my old one. Just trying to work on a Discord bot....

**Comment by mythicalbadger** [comment]
Nevermind, the solution was to just Ctrl^C out when the Python part was reached....

**Comment by zanderwar** [comment]
I left this running overnight lol, 8 hours later

> Still waiting for installer log file...

Ctrl^C 

> Now configuring the Visual Studio Build Tools and Python...

lol

**Comment by SkyeRangerDelta** [comment]
I've got this same issue, except hitting Ctrl^C after a significant amount of time doesn't progress the install/wait. It asks to terminate the batch job and then proceeds to terminate it despite whatever you chose (Y/N).

I've re-run the command with `--verbose` and `--loglevel silly` and even went as far as to add `--debug` only to get no different responses at this point (`--debug` just constantly spits out 'still waiting on installer log file').

Any further tips on this would be fantastic. Windows Build Tools / whatever node-gyp uses has been a pain in my neck for the past week and has ground development to a hault.
