### ISSUE TITLE
Visual Studio Build Tools 2018/2019?

### ISSUE THREAD

**Issue by Baterka** [felixrieseberg/windows-build-tools#195]
When 2018/2019  Build Tools coming?

**Comment by jacobq** [comment]
I haven't seen any active development on this project recently, so I wouldn't hold my breath if I were you. (Felix is evidently busy with many other responsibilities, so it is really up to the community to pitch in right now.) However, it's worth noting that support for building node modules with VS 2019 didn't arrive until Node v13.x (see https://github.com/nodejs/node/pull/30022) so it wouldn't work for most people.

Is there some problem or limitation with the current version or were you just curious / wanting to update for the sake of updating?

**Comment by jacobq** [comment]
Duplicate -- closing in favor of #194
