### ISSUE TITLE
the host is unavaliable

### ISSUE THREAD

**Issue by liupuchun** [felixrieseberg/windows-build-tools#217]
![image](https://user-images.githubusercontent.com/35803206/83487290-5b9d8900-a4dd-11ea-9682-c6c941778a86.png)

the link [download.visualstudio.microsoft.com](http://download.visualstudio.microsoft.com) deaded.
error code :500 - Internal Server Error

**Comment by liupuchun** [comment]
download.visualstudio.microsoft.com

**Comment by jacobq** [comment]
The `getaddrinfo` error you showed means there was a problem resolving the hostname `download.visualstudio.microsoft.com` to an IP address. This is usually a temporary problem related to the network you are using. The fact that you were able to get an HTTP 500 error (different problem -- would've seen something like "Cannot connect to server" or "Connection timed out" instead) demonstrates that the name resolved correctly. Please try again and see if the DNS failure persists.

Also note that `download.visualstudio.microsoft.com` is only the [host portion](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax) of the URL for downloading the build tools. It is not the full link. Se https://github.com/felixrieseberg/windows-build-tools/blob/v5.2.2/src/constants.ts#L38

```
C:\Users\jacob\Downloads>nslookup download.visualstudio.microsoft.com
Server:  cdns01.comcast.net
Address:  2001:558:feed::1

Non-authoritative answer:
Name:    cs10.wpc.v0cdn.net
Addresses:  2606:2800:11f:7de:d31:7db:168f:1225
          93.184.215.201
Aliases:  download.visualstudio.microsoft.com
          2-01-5830-0005.cdx.cedexis.net
          4316b.wpc.azureedge.net
```

**Comment by liupuchun** [comment]
> The `getaddrinfo` error you showed means there was a problem resolving the hostname `download.visualstudio.microsoft.com` to an IP address. This is usually a temporary problem related to the network you are using. The fact that you were able to get an HTTP 500 error (different problem -- would've seen something like "Cannot connect to server" or "Connection timed out" instead) demonstrates that the name resolved correctly. Please try again and see if the DNS failure persists.
> 
> Also note that `download.visualstudio.microsoft.com` is only the [host portion](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax) of the URL for downloading the build tools. It is not the full link. See https://github.com/felixrieseberg/windows-build-tools/blob/v5.2.2/src/constants.ts#L38
> 
> ```
> C:\Users\jacob\Downloads>nslookup download.visualstudio.microsoft.com
> Server:  cdns01.comcast.net
> Address:  2001:558:feed::1
> 
> Non-authoritative answer:
> Name:    cs10.wpc.v0cdn.net
> Addresses:  2606:2800:11f:7de:d31:7db:168f:1225
>           93.184.215.201
> Aliases:  download.visualstudio.microsoft.com
>           2-01-5830-0005.cdx.cedexis.net
>           4316b.wpc.azureedge.net
> ```

sincerely thanks!It actually is the hostname,I was stupid.Now I used proxy and it works.

**Comment by jacobq** [comment]
No worries, good luck, and sorry for not helping keep this project up to date (it's been suffering from neglect for about a year now).
