### ISSUE TITLE
Error on Windows XP

### ISSUE THREAD

**Issue by jsmart523** [felixrieseberg/windows-build-tools#22]
I'm trying to install this on an old machine.

When I type...
> npm install --global --production windows-build-tools > output.log

... the response on the console is...

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn powershell.exe ENOENT
>     at exports._errnoException (util.js:907:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
>     at onErrorNT (internal/child_process.js:344:16)
>     at nextTickCallbackWith2Args (node.js:442:9)
>     at process._tickCallback (node.js:356:17)
>  npm ERR! Windows_NT 5.1.2600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--production" "windows
> -build-tools"
> npm ERR! node v4.5.0
> npm ERR! npm  v2.15.9
> npm ERR! code ELIFECYCLE
> ...`

Here are the files created:
* [output.log](https://github.com/felixrieseberg/windows-build-tools/files/429038/output.txt)
* [npm-debug.log](https://github.com/felixrieseberg/windows-build-tools/files/429039/npm-debug.txt)

Any ideas on what to try?

**Comment by A92hm** [comment]
Do you have PowerShell installed?

**Comment by jsmart523** [comment]
Nope. PowerShell is not installed.

If PowerShell is a requirement then I'd request that this be reflected in the install section of README.md, caught and explained within the install process, or preferably both.

**Comment by A92hm** [comment]
Yeah I will add that. PowerShell comes with Windows 8 and above, that's why we don't have it in the readme.

Did installing PowerShell solve your problem?

**Comment by felixrieseberg** [comment]
Even if we get PowerShell to run, I'm afraid that the new tools simply won't run on a Windows that old. Remember that it was released __15 years__ - I'm sorry, but I don't think we'll ever support it.
