### ISSUE TITLE
Installs Python 2.7

### ISSUE THREAD

**Issue by ashk3301** [felixrieseberg/windows-build-tools#222]
The readme says this installs python 3.8 but the tool installs python 2.7.x. Please update the readme to display that it will install python 2.7. I had to stop downloading in between when I saw that it is downloading python 2.7. And now I have no idea whether the partially downloaded python 2.7 file is there on my system and will it create issues?.

Note- I already have python 3.8 installed on my system.
The python file was inside C:\\Users\{Your-user}\.windows-build-tools

**Comment by jacobq** [comment]
The README you're looking at is for the `master` branch. The latest [`npm` release](https://www.npmjs.com/package/windows-build-tools/v/5.2.2?activeTab=versions) is behind (5.2.2). You can browse the repository (including `README.md`) at this version here: https://github.com/felixrieseberg/windows-build-tools/tree/v5.2.2
