### ISSUE TITLE
I am not opposed to this, but I would like to better understand what value you believe this provides. I don't want to mislead users into mistakenly thinking that this would be an indication of the security audit status of **the software that `windows-build-tools` installs**.

### ISSUE THREAD

**Issue by martinpj89** [felixrieseberg/windows-build-tools#237]
I am not opposed to this, but I would like to better understand what value you believe this provides. I don't want to mislead users into mistakenly thinking that this would be an indication of the security audit status of **the software that `windows-build-tools` installs**.

_Originally posted by @jacobq in https://github.com/felixrieseberg/windows-build-tools/issues/231#issuecomment-749595063_

**Comment by jacobq** [comment]
What is the meaning of this issue? (What is the desired action??) My comment was in response to a PR.
