### ISSUE TITLE
[QUESTION] Is this package necessary when using nvm? If so, should I install it for every version of Node?

### ISSUE THREAD

**Issue by leafac** [felixrieseberg/windows-build-tools#239]
I’m using https://github.com/coreybutler/nvm-windows/ to manage multiple versions of Node. I have a couple of questions:

1. Does nvm subsume windows-build-tools, or should I install windows-build-tools anyway?
2. If I should install windows-build-tools, then should I install it [for every version of Node](https://github.com/coreybutler/nvm-windows#reinstall-any-global-utilities) or just once is enough? (After all, windows-build-tools is **not** a command-line tool.)

I’m asking the same question over at the nvm repository: https://github.com/coreybutler/nvm-windows/discussions/627

**Comment by jacobq** [comment]
They are independent, so no and no.
`windows-build-tools` is intended as a convenience for installing some 3rd party software (e.g. python, MS Build Tools, ...). In this way it is not like most other node modules. I hope that answers you questions. Unfortunately, this package is also becoming more and more out of date as no one has been investing time in improving/maintaining it, and the owner associated with the module on npm has not been responding.

**Comment by leafac** [comment]
Okay, so I’ll install `windows-build-tools`, but just once.

Thanks for the quick answer.

It’s too bad this may not work in the future; it’s so convenient!
