### ISSUE TITLE
Installer stuck after printing out 'Successfully installed Visual Studio Build Tools' on windows 10

### ISSUE THREAD

**Issue by curtwagner1984** [felixrieseberg/windows-build-tools#27]
![powershell_2016-10-02_15-13-42](https://cloud.githubusercontent.com/assets/20076369/19020499/2480927c-88b3-11e6-9847-0cf1cb130eb3.jpg)

I know it says 'This would take some time' but I left it on for a night, and it's still in this position, so I don't think it's just impatience on my part.

**Comment by felixrieseberg** [comment]
Hm, sorry to see that you're having trouble - it looks like Python doesn't install correctly. Could you tell me what you see in the folder `%USERPROFILE%\.windows-build-tools`?

**Comment by curtwagner1984** [comment]
This:
![explorer_2016-10-06_17-16-32](https://cloud.githubusercontent.com/assets/20076369/19155931/de0cab3a-8be8-11e6-824b-a309fb8fb2cf.jpg)
[build-tools-log.txt](https://github.com/felixrieseberg/windows-build-tools/files/513961/build-tools-log.txt)
[python-log.txt](https://github.com/felixrieseberg/windows-build-tools/files/513960/python-log.txt)

**Comment by davidreghay** [comment]
Hi, I'm having the same problem on windows 10 as well.  Here's my `%USERPROFILE%\.windows-build-tools` directory

![image](https://cloud.githubusercontent.com/assets/7400455/19368480/2c2613e4-916e-11e6-81ed-2055310e4b4c.png)

**Comment by christlee1989** [comment]
me too....

![image](https://cloud.githubusercontent.com/assets/10151385/19422771/f84862b2-944b-11e6-9ea6-67a85813c45d.png)

**Comment by davidreghay** [comment]
Hi all,

I've attached some of the relevant logs here after trying again today: 

[python-log.txt](https://github.com/felixrieseberg/windows-build-tools/files/539903/python-log.txt)
[build-tools-log.txt](https://github.com/felixrieseberg/windows-build-tools/files/539902/build-tools-log.txt)

Any help on this is greatly appreciated.  The only thing that seems to indicate any kind of problem in the logs are the following lines from `python-log.txt` : 

```
Action start 14:34:45: PublishProduct.
MSI (s) (48:60) [14:34:45:214]: Product: Python 2.7.11 -- Error 1316. The specified account already exists.


Error 1316. The specified account already exists.

Action ended 14:34:45: PublishProduct. Return value 3.
Action ended 14:34:45: INSTALL. Return value 3.
```

This seems to indicate that there was some kind of registry conflict after a (partial?) install of python 2.7.11 (via the windows-build-tools? I'm not sure...)  Anyway, I'm going to try uninstalling python 2.7.11 through the control panel and try running the windows-build-tools install again and see if that works.  I'll report back here to let you know.

**Comment by davidreghay** [comment]
@curtwagner1984, @felixrieseberg : I want to let you know that the above worked for me.  I hope this resolves the issue for others with similar problems!  By the way, it also seems that I may have run into some problems with this earlier due to conflicts between the script and Git Bash shell (instead of windows powershell) although I can't be sure about that.

Ciao,
David

**Comment by curtwagner1984** [comment]
@davidreghay That did the trick for me! Thank you!
