### ISSUE TITLE
installation fail due to undefined exception.

### ISSUE THREAD

**Issue by Mo33n** [felixrieseberg/windows-build-tools#28]
Downloaded python-2.7.11.msi. Saved to C:\Users\Moeen.windows-build-tools\python-2.7.11.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... |C:\Users\Moeen\AppData\Roaming\npm\node_modules\windows-build-tools\lib\install\tailer.js:92
      if (data.includes('Variable: IsInstalled = 1') || data.includes('Variabl
               ^
TypeError: undefined is not a function
    at Tailer.handleData (C:\Users\Moeen\AppData\Roaming\npm\node_modules\windows-build-tools\lib\install\tailer.js:92:16)
    at null.<anonymous> (C:\Users\Moeen\AppData\Roaming\npm\node_modules\windows-build-tools\lib\install\tailer.js:72:16)
    at wrapper [as _onTimeout](timers.js:265:14)
    at Timer.listOnTimeout (timers.js:110:15)

**Comment by felixrieseberg** [comment]
Hey, are you using a slightly older version of Node? If so, upgrading Node will fix your issues 👍

**Comment by daveprochnow** [comment]
I am getting the exact same error, but the work is being done for an organization that requires that we use Node 0.12.  Is it possible to get things working using manual configuration of Python and VS?

**Comment by daveprochnow** [comment]
I am getting the exact same error, but the work is being done for an organization that requires that we use Node 0.12.  Is it possible to get things working using manual configuration of Python and VS?

**Comment by daveprochnow** [comment]
Ok, I answered my own question.  If you cannot get the windows-build-tools package to work, you can still get things running okay.  For the version of Node we're using, I had to revert to Visual Studio 2013.
