### ISSUE TITLE
Not success on Windows 10

### ISSUE THREAD

**Issue by keyiis** [felixrieseberg/windows-build-tools#29]
I installed windows-build-tools follow Instruction and my computer already install python 2.7.9 vs2015,but when i install any native addon(sqlite3,pinyin),get similar error,my env:
os:win10 x64
nodejs:6.9.1
error:
```
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  index.cpp
  nodejieba.cpp
  win_delay_load_hook.cc
c:\users\administrator\.node-gyp\6.9.1\include\node\v8.h(800): fatal error C107
0: 文件“c:\users\administrator\.node-gyp\6.9.1\include\node\v8.h”中的 #if/#endif 对不
匹配 (编译源文件 ..\lib\index.cpp) [D:\work\nodejs\angular\angular2-electron\node_modu
les\nodejieba\build\nodejieba.vcxproj]
c:\users\administrator\.node-gyp\6.9.1\include\node\v8.h(800): fatal error C107
0: 文件“c:\users\administrator\.node-gyp\6.9.1\include\node\v8.h”中的 #if/#endif 对不
匹配 (编译源文件 ..\lib\nodejieba.cpp) [D:\work\nodejs\angular\angular2-electron\node_
modules\nodejieba\build\nodejieba.vcxproj]
```
nodejieba belong to pinyin.

**Comment by ileenhow** [comment]
@keyiis I meet the similar problem when I install opencc, fix it after installing windows 10 sdk seperately

**Comment by keyiis** [comment]
@ileenhow i uninstall nidejs6.9 and install nodejs 4.6,the issues fixed.

**Comment by iamsaurabhc** [comment]
Open the terminal with Administrative rights. That helped me!

**Comment by keyiis** [comment]
@iamsaurabhc it doesn't work.i already fied,thanks reply!
