### ISSUE TITLE
Estimated Size

### ISSUE THREAD

**Issue by OleVik** [felixrieseberg/windows-build-tools#30]
Is there any estimated size for installing the [contents](https://github.com/felixrieseberg/windows-build-tools#contents)? I have previously installed them a few times, manually, and then the size seemed to be between 4 and 6 GB. For many systems it is not an issue, but for smaller ones constrained by available space it is.

**Comment by felixrieseberg** [comment]
Sorry, sadly not - because the size heavily depends on your OS, the platform, and what you already have installed. If size is a constraint the full build tools will probably always be troublesome, though...
