### ISSUE TITLE
getaddrinfo ENOTFOUND download.microsoft.com download.microsoft.com:80 while installing build tools .. kindly help here

### ISSUE THREAD

**Issue by ionicappworld** [felixrieseberg/windows-build-tools#31]
Downloading BuildTools_Full.exe
Error: getaddrinfo ENOTFOUND download.microsoft.com download.microsoft.com:80
{ [Error: getaddrinfo ENOTFOUND download.microsoft.com download.microsoft.com:80
]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'download.microsoft.com',
  host: 'download.microsoft.com',
  port: 80 }

**Comment by felixrieseberg** [comment]
Hm, seems like you're having trouble connection to Microsoft, but the link is up. Check your internet connection!
