### ISSUE TITLE
Windows-build-tools install failing on Windows 10 due to "adminstrative PowerShell" issue

### ISSUE THREAD

**Issue by davidj-RTP** [felixrieseberg/windows-build-tools#32]
I am having trouble installing windows-build-tools on my windows 10 pc.  I am the only user and have full admin rights.  
Error message includes directions to "Please restart this script from an administrative PowerShell!"
I have added path.  packaged download but won't install.

Suggestions?

![screen capture windows-build-tools problem](https://cloud.githubusercontent.com/assets/18272648/19983511/89055ac0-a1c7-11e6-8129-016b7e322e53.PNG)

**Comment by davidj-RTP** [comment]
I ran also ran 'npm install windows-build-tools' from the powershell, with the same results

**Comment by felixrieseberg** [comment]
You need to right-click the PowerShell icon and select 'Run as Administrator'.

**Comment by davidj-RTP** [comment]
Thanks.  I did figure that out and I was going to update the ticket.  Windows build tools did install (I think, not sure, hard to validate.). Having trouble loading other components needed for ijavascript.
