### ISSUE TITLE
can't install on Windows 10. Nodejs 7.1.0

### ISSUE THREAD

**Issue by halcyonl** [felixrieseberg/windows-build-tools#35]

**Comment by ironmanwaring** [comment]
Here's the logs and exception from the command that I'm getting - the command still works in 7.0.0

C:\WINDOWS\system32>npm i -g windows-build-tools

> windows-build-tools@0.6.0 postinstall C:\Program Files\nodejs\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.11.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.11.msi. Saved to C:\Users\phill\.windows-build-tools\python-2.7.11.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... |Successfully installed Visual Studio Build Tools.
Successfully installed Python 2.7
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (C:\Users\phill\AppData\Roaming\nvm\v7.1.0\node_modules\windows-build-tools\node_modules\single-line-log\index.js:12:16)
    at process.<anonymous> (C:\Users\phill\AppData\Roaming\nvm\v7.1.0\node_modules\windows-build-tools\node_modules\single-line-log\index.js:17:29)
    at emitOne (events.js:101:20)
npm ERR! Windows_NT 10.0.14931
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "windows-build-tools"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! windows-build-tools@0.6.0 postinstall: `node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@0.6.0 postinstall script 'node ./lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-build-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by ironmanwaring** [comment]
It looks like the cause is in Node 7.1.0 itself:  https://github.com/nodejs/node/issues/9542

**Comment by felixrieseberg** [comment]
☝️ You are correct, there's little we can do - but given that all kinds of tools are broken with Node 7.1, I'd recommend going with Node 7 instead.

**Comment by Rohail1** [comment]
I have the same issue. Node 7.1 and windows 10.  When can we expect a fix ?

**Comment by felixrieseberg** [comment]
It's already out: Just update to Node 7.2. The error was in Node, so there was nothing we could do here.

**Comment by realtebo** [comment]
You should support last LTS of node. Imho.  A lot of company cannot simply switch to another version without heavy testina.

**Comment by felixrieseberg** [comment]
@realtebo: LTS is still on Node 6, which is totally supported. *Only* Node 7.1 is faulty, simply due to an error inside the Node codebase, not with this module.
