### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ifishing** [felixrieseberg/windows-build-tools#36]
C:\Windows\system32>npm install -g windows-build-tools

> windows-build-tools@0.6.0 postinstall C:\Users\fisher\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.11.msi
[============================================>] 100.0% of 18.64 MB (6.09 kB/s)
Downloaded python-2.7.11.msi. Saved to C:\Users\fisher\.windows-build-tools\python-2.7.11.msi.
Starting installation...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn powershell.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\ProgramFiles\\Node.js\\node.exe" "C:\\Users\\fisher\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "windows-build-tools"
npm ERR! node v6.9.1
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE

npm ERR! windows-build-tools@0.6.0 postinstall: `node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@0.6.0 postinstall script 'node ./lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-build-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by felixrieseberg** [comment]
`Error: spawn powershell.exe ENOENT`

☝️ This error means that Node couldn't spawn PowerShell. What version of Windows are you on? Did you try to run this tool from PowerShell?

**Comment by ifishing** [comment]
My windows version is Window7 with Service Pack 1. 
Running the command in  CMD or PowerShell both will throw the exception.
I  resolved it by running it in PowerShell which is run as administrator.
