### ISSUE TITLE
Need a way to get proxy settings to nugget

### ISSUE THREAD

**Issue by JasonCubic** [felixrieseberg/windows-build-tools#37]
You should either check the npm environment proxy setting and pass that to nugget or allow a --proxy setting from the command line call to be able to be passed to the nugget call.

I'm behind a corp firewall and this script fails when nugget tries to download files because the proxy settings are not being used.

**Comment by felixrieseberg** [comment]
No worries! You can just set a PROXY environment variable. On PowerShell, just call this `$env:PROXY=YOURPROXY`.
