### ISSUE TITLE
issue installing bcrypt

### ISSUE THREAD

**Issue by SaqlainGardezi** [felixrieseberg/windows-build-tools#38]
I am getting this error
 else (node "" rebuild )
E:\notepad\node\Fast Record\nodeauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj(20,3): error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Whatshould I do?

**Comment by Blair2004** [comment]
wondering if somebody has solved this yet

**Comment by jacobq** [comment]
Is this a `windows-build-tools` issue? (Does it work if you manually install the tools?)

**Comment by Blair2004** [comment]
i've added the flag `--production` while installing windows-build-tools and it's okay now :)

**Comment by jacobq** [comment]
Closing due to age / inactivity
