### ISSUE TITLE
The term 'python' is not recognized

### ISSUE THREAD

**Issue by shawmanz32na** [felixrieseberg/windows-build-tools#39]
After successfully installing windows-build-tools, my node-gyp installations are still failing with the following error:

```
gyp ERR! stack Error: Can't find Python executable "C:\Users\Development\.windows-build-tools\python27", you can set the PYTHON env variable.
```

I manually added the .windows-build-tools directory to my user's environment variables as `PYTHON`, and `$env:PYTHON` resolves appropriately.

Yes, I did try restarting my box.

Am I missing something? Should I have done something differently? Is this a bug?

**Comment by A92hm** [comment]
Can you run the following command and paste the output here?
```bash
$ npm config get python
```

**Comment by felixrieseberg** [comment]
I'm closing this now, seems a bit stale 📖

**Comment by shawmanz32na** [comment]
Sounds good. If I get around to debugging a bit, I'll open a new issue.
