### ISSUE TITLE
Hangs when installed via Chef

### ISSUE THREAD

**Issue by zrisher** [felixrieseberg/windows-build-tools#45]
Normally I can install any NPM package via Chef using an `execute` or `batch` resource and a local npm install in my path. For example:

```
execute "test npm install with node-gyp" do
  code "call npm install --global node-gyp"
end
```

works just fine.

However, this particular package always hangs the Chef process:

```
execute "test npm install windows-build-tools" do
  command "call npm install --global windows-build-tools"
end
```

This gets me to the end of the install process and then just hangs indefinitely (at least 2 hours):

```
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... /Successfully installed Visual Studio Build Tools.
Successfully installed Python 2.7
```

Full example here: http://pastebin.com/qHdAciqP

I can't reproduce this using npm via a local cmd, ps, or bat script, but it always occurs using the local chef client.

I've tried various combinations of `call`, `start`, `cmd`, and `exit` with no luck running this npm install without hanging the running process. The closest I've gotten was 

```start npm install -g windows-build-tools``` 

which starts the process in a separate window, where it successfully completes but never closes. If I type `exit 0` in that window, it returns control to the chef process which successfully completes its run. But I can't find a way to  accomplish this programmatically. 

I note it's also a little strange that `start npm install -g windows-build-tools` forces Chef to wait for the process to complete with an `exit`, whereas `start` shouldn't block the current process unless `/WAIT` is supplied.

I'm guessing there's some windows scripting control flow going on in the `windows-build-tools` install that fails to fully return control to the calling process, but I'm not super familiar with Windows administration. 

Since this only occurs with this package, I believe this isn't a Chef or NPM issue, but rather a complex conflict between some behavior in this specific package and the way those tools are used on Windows.

Related: https://github.com/npm/npm/issues/2938

I would greatly appreciate any advice on how I might get this working.

**Comment by zrisher** [comment]
Quick update here - using Chef's tracing functionality I narrowed the issue down to this code:

[mixlib-shellout/lib/mixlib/shellout/windows.rb](https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout/windows.rb)
```
def run_command
...
  loop do
    wait_status = WaitForSingleObject(process.process_handle, 0)
    ...
    when WAIT_OBJECT_0
       # Exit, etc...
       ...
    when WAIT_TIMEOUT
       ...
       consume_output(open_streams, stdout_read, stderr_read)
       ...
    end
  ...
  end
```
and then consume output is continually running these three lines:
```
def consume_output(open_streams, stdout_read, stderr_read)
        return false if open_streams.length == 0
        ready = IO.select(open_streams, nil, nil, READ_WAIT_TIME)
        return true if ! ready
```

[`WaitForSingleObject`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687032(v=vs.85).aspx) and [`IO.select`](https://ruby-doc.org/core-2.0.0/IO.html#method-c-select) are lower level functions, but I think the gist is clear:

**running `npm install -g windows-build-tools` remains in a perptual WAIT signaled state even after completion.**

@felixrieseberg This is definitely an issue with this library, since it's different behavior than every other node package.

**Comment by zrisher** [comment]
More info:

Since npm allows you to install from git, I forked this repo and tested changes to the code to attempt to fix the above issue. 

To my surprise, the issue disappeared when I commented out all the logging lines in `lib/index.js`. Simple variable assignment worked fine, but any logging would cause this issue. 

Further, if I leave `lib/index.js` untouched and point the `postinstall` script to a different file without any logging, the issue is fixed: https://github.com/zrisher/windows-build-tools/commit/75d761228c8a0d0d9d97aba4b6544ed01d39548a

If I add add a `console.log()`, however, the issue reappears: https://github.com/zrisher/windows-build-tools/commit/62f8cdd200bdbbbf34453a92d2ec07c62fd90e61

So I've narrowed the issue down to calling `console.log()` within the `postinstall` script. But why this occurs... I still have no idea.

**Comment by felixrieseberg** [comment]
Hey! Sorry to hear that you're having trouble - I'm wondering if Chef just does something weird to the terminal. Who knows. Thanks for the detailed report though!

I went ahead and added a `silent` option (see readme) and released it in 1.1.0. I'm hoping that it'll fix your issue - mind giving it a spin?

**Comment by zrisher** [comment]
@felixrieseberg Thanks so much for taking a look. Unfortunately that does not solve the issue. I think it's not so much the call to `console.log()` but rather calling a specific level of logic within that file in general. I suspect it has something to do with the additional calls to `npm` and `node` within the script definitions, because normally those commands need to be prepended with `call` on windows to properly pass their execution environment back to a remote administration tool. 

I'll start looking at the exact steps that "npm install -g package_name" takes and try to reproduce the issue further into the call stack.

**Comment by zrisher** [comment]
@felixrieseberg Confirmed, calling `call npm run-script some_script` will always block the chef client with  `"some_script": "node ./lib/index.js"` and a `console.log()` within `index.js`. A minimal example repo: https://github.com/zrisher/chef-npm-example.

So this this isn't your repo's fault, though hopefully there's a syntax fix I can apply once I figure this one out with the help of the chef and npm communities.

**Comment by zrisher** [comment]
Closing this issue, since the core problem is with Chef and not this repo. Thanks @felixrieseberg for your help - I'm sure the `--silent` option you added will still be of use to others.
