### ISSUE TITLE
error when installing python

### ISSUE THREAD

**Issue by lofar968** [felixrieseberg/windows-build-tools#49]
tried to install via PowerShell run as admin

PS C:\Users\Thaem\Desktop\coding projects\lagooner> npm install --global --production windows-build-tools

> windows-build-tools@1.2.0 postinstall C:\Users\Thaem\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.11.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.11.msi. Saved to C:\Users\Thaem\.windows-build-tools\python-2.7.11.msi.
Starting installation...
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: spawn powershell.exe ENOENT
    at exports._errnoException (util.js:1023:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "--global" "--production" "windows-build-tools"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! windows-build-tools@1.2.0 postinstall: `node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@1.2.0 postinstall script 'node ./lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-build-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Thaem\Desktop\coding projects\lagooner\npm-debug.log

**Comment by felixrieseberg** [comment]
Hey! Which version of Windows are you on? The error here is that Node can't find PowerShell.

**Comment by lofar968** [comment]
Windows 10 Pro version 1511 and OS build 10586.633

**Comment by felixrieseberg** [comment]
If you open up cmd - and type `powershell.exe`, does that work?

**Comment by lofar968** [comment]
not recognized as an internal or external, command, operable batch file.

**Comment by lofar968** [comment]
I fixed it by adding PowerShell.exe to the PATH environment variable.

**Comment by DRakeshKumar** [comment]
I am also finding the same error.. what is the solution?
