### ISSUE TITLE
Remove build tools completely.

### ISSUE THREAD

**Issue by happilymarrieddad** [felixrieseberg/windows-build-tools#51]
Hey guys I accidently installed windows built tools using a 32bit nodejs msi. How do I uninstall everything and install with a 64bit installer. Everytime I build it says it is not a win32 app because I have to use node 64 for the package I'm using. Thanks!

**Comment by felixrieseberg** [comment]
You can find the build tools in your `Programs & Features` settings in Windows (where you'd uninstall anything else).

**Comment by happilymarrieddad** [comment]
Yea I know that but it doesn't uninstall all the dependencies. The build tools and whatnot were installed as 32bit and therefore won't work with a 64bit installation. I removed all the dependencies that I saw in the Programs and Features but there must be something else somewhere else. It still doesn't allow me to build 64bit packages that work. Basically, I need to know what dependencies the build tools install so I can remove everything. Thanks!
