### ISSUE TITLE
Install uninstalled my Python?

### ISSUE THREAD

**Issue by spazmodius** [felixrieseberg/windows-build-tools#52]
I had Python 2.7 installed in `C:\Program Files (x86)\Python27`.  After installing `windows-build-tools`, that folder is mostly empty, except for `Lib` and `Scripts` directories.

**Comment by vvuk** [comment]
I just had this exact same thing happen.  I had Python installed in `C:\Python27`; it has disappeared (other than left-behind Lib/Scripts), which an entry in my Programs & Features saying that Python 2.7.13 was installed just now (which is what this package installs).  I have no idea where the python that this package installed even went.

**Comment by vitaminj** [comment]
Same problem as vvuk.
Windows 10 16299.19, node 6.10.0, npm 3.10.10
I deleted my Python27 dir and re-ran the windows-build-tools installer with --add-python-to-path to use that (it puts it in %USER%\.windows-build-tools\python27\ for reference)

**Comment by unformatt** [comment]
This is absurd. If Python 2.7 is already installed on the system why reinstall? When the Python installer ran, it **killed running python scripts**. So not only did `windows-build-tools` remove Python from my system but it killed a database migration script that was running, leaving my production database in a bad state. This is my punishment for trying to migrate my database while also `npm i` ? Extremely careless.

It's a miracle one of my devs actually tracked this down. It happened once before and we just wondered "What ghost removed python from the server?"

**Comment by jacobq** [comment]
@unformatt I am sorry about the bad experience you've had with this. Though I have no idea why you are installing these build tools in production I agree that we should add some options regarding which version of Python should be installed, if any, and to what location it should be installed. (I have seen this mentioned in multiple issues lately too.)

I personally haven't run into this (my use case for this is mainly just CI builds) nor have I had time to look into it yet. Would you or your colleague be willing to share more details here to speed things along? (For example, I suspect that it is the Python installer we launch that defaults to uninstalling when Python is already installed, but it would be nice if you could confirm this.) A pull request would also be welcome.

**Comment by jacobq** [comment]
Looks like we install using `python-2.7.14.amd64.msi /?` so have [standard `msiexec` options](https://msdn.microsoft.com/en-us/library/windows/desktop/aa367988(v=vs.85).aspx):
<summary><details>

```
Windows ® Installer. V 5.0.16299.15 

msiexec /Option <Required Parameter> [Optional Parameter]

Install Options
	</package | /i> <Product.msi>
		Installs or configures a product
	/a <Product.msi>
		Administrative install - Installs a product on the network
	/j<u|m> <Product.msi> [/t <Transform List>] [/g <Language ID>]
		Advertises a product - m to all users, u to current user
	</uninstall | /x> <Product.msi | ProductCode>
		Uninstalls the product
Display Options
	/quiet
		Quiet mode, no user interaction
	/passive
		Unattended mode - progress bar only
	/q[n|b|r|f]
		Sets user interface level
		n - No UI
		b - Basic UI
		r - Reduced UI
		f - Full UI (default)
	/help
		Help information
Restart Options
	/norestart
		Do not restart after the installation is complete
	/promptrestart
		Prompts the user for restart if necessary
	/forcerestart
```
</details></summary>

and [we are specifying the `/i` option](https://github.com/felixrieseberg/windows-build-tools/blob/master/ps1/launch-installer.ps1#L50) so I'm surprised that it would uninstall. Would anyone who has experienced this be willing to share their `python-log.txt` file?

**Comment by unformatt** [comment]
@jacobq Willing to help however I can. I've seen the uninstall problem twice but when I just tried to create it, it did not uninstall. So, I don't have much evidence. But I have a couple screenshots:

![image](https://user-images.githubusercontent.com/157132/36050774-caa6b82e-0db5-11e8-83cc-3c20704a4c8a.png)

Original Python folder with executables and libs removed:

![image](https://user-images.githubusercontent.com/157132/36050791-dbae67fc-0db5-11e8-90d5-2e2636cd6a73.png)


Installer event:

![image](https://user-images.githubusercontent.com/157132/36050852-1c113180-0db6-11e8-8cdd-cc367e968036.png)

RestartManager (not sure what actually does) trying to restart missing python after install?

![image](https://user-images.githubusercontent.com/157132/36050890-424f695c-0db6-11e8-80fd-4d5ac39e63a6.png)
