### ISSUE TITLE
Why not Python3?

### ISSUE THREAD

**Issue by tats-u** [felixrieseberg/windows-build-tools#58]
This package seems to install Python 2.7, but it is supported for only 3 years. (Support is expired in 2020.  See https://pythonclock.org/)  Is there a plan to upgrade Python to the version 3?

**Comment by coagmano** [comment]
Since this package exists to enable [`node-gyp`](https://github.com/nodejs/node-gyp#installation), I imaging it will install python 3 when `node-gyp` requires python 3

Right now `node-gyp` says quite explicitly:

> Install Python 2.7 (v3.x.x is not supported), and run npm config set python python2.7

**Comment by tats-u** [comment]
I got it, so I will throw a issue there.  Thank you.

**Comment by felixrieseberg** [comment]
@coagmano Thanks for jumping in!
