### ISSUE TITLE
Possibility to install several versions of build tools

### ISSUE THREAD

**Issue by Flarna** [felixrieseberg/windows-build-tools#6]
Is there any option to install several versions of the build tools on the same PC?

I'm thinking of a setup where latest builds use the latest compiler but older releases stick on an older version.

**Comment by felixrieseberg** [comment]
I'm sorry, I don't that's currently possible (given where we are with the C++ build tools).

**Comment by Flarna** [comment]
ok thanks. Would be nice to get this in future.
