### ISSUE TITLE
How avoid download again the package and install from %USERPROFILE%\.windows-build-tools

### ISSUE THREAD

**Issue by ceoaliongroo** [felixrieseberg/windows-build-tools#60]
There is a parameter to avoid the download of the installers?

I have already the installers cached in `%USERPROFILE%\.windows-build-tools`. And the  parameter `--resume` didn't works .

**Comment by jacobq** [comment]
This is a good idea, and I'm planning to make a PR that incorporates it soon. Since there is another issue open regarding this (even though it's newer) I'm going to close this one.
https://github.com/felixrieseberg/windows-build-tools/issues/88
