### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by 3choBoomer** [felixrieseberg/windows-build-tools#63]
attempting to install on Windows 2012
node 0.12.2
npm 3.10.10

`PS C:\Windows\system32> npm install --global windows-build-tools

> windows-build-tools@1.3.2 postinstall C:\Program Files\nodejs\node_modules\windows-build-tools
> node ./lib/index.js

C:\Users\dev-services\AppData\Roaming\nvm\v0.12.2\node_modules\windows-build-tools\node_modules\fs-extra\lib\index.js:3
const assign = require('./util/assign')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\dev-services\AppData\Roaming\nvm\v0.12.2\node_modules\windows-build-tools\lib\utils.
js:3:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "--global" "windows-build-tools"
npm ERR! node v0.12.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! windows-build-tools@1.3.2 postinstall: `node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@1.3.2 postinstall script 'node ./lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-build-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log`

**Comment by felixrieseberg** [comment]
Please update to a recent Node version. 0.12 is no longer supported by Node and neither by this module.

https://github.com/nodejs/LTS

**Comment by PRINCEHR** [comment]
Does Not Work

**Comment by erikusaj** [comment]
same issue on  both Node LTS and latest:
node --version
v8.2.1

`
Starting installation...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn powershell.exe ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@1.3.2 postinstall: `node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@1.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by pestig** [comment]
same issue here, run cmd as Administartor fixed the problem.

**Comment by cnscorpions** [comment]
@pestig not work to run as Admin for both cmd, powershell, and any other terminals

**Comment by jacobq** [comment]
@erikusaj's problem appears to be caused by `powershell.exe` not being in the user's path (see https://github.com/felixrieseberg/windows-build-tools/issues/20). 

@cnscorpions Would you mind opening a new issue with your specific details? Ensure you are using Node >= 8.x, start a PowerShell session as Administrator, and run `npm install --global windows-build-tools`. If it fails please share the output as well as any other relevant information.
