### ISSUE TITLE
is there a flag to close python installation. because I have installed python in my environment?

### ISSUE THREAD

**Issue by someja** [felixrieseberg/windows-build-tools#67]
is there a flag to close python installation. because I have installed python in my environment?

**Comment by crashspringfield** [comment]
I'm running to an issue because of this too. I don't have admin privileges, so it fails on 
    `Downloaded python-2.7.13.msi.` 
    `Starting installation...`

**Comment by arc12** [comment]
+1 to a command line flag to skip python installation.
I already have this and dont want another; it just wastes time and space and makes things more dirty.

**Comment by jacobq** [comment]
I don't think this is currently possible but believe it is planned as a future feature. See also https://github.com/felixrieseberg/windows-build-tools/issues/53

**Comment by felixrieseberg** [comment]
For reference, we're no longer installing Python if it's already present.
