### ISSUE TITLE
Remove C++ Build Tools and Python when tool is removed

### ISSUE THREAD

**Issue by kimbaudi** [felixrieseberg/windows-build-tools#68]
I installed windows-build-tools using the following command:
`npm install --global --production windows-build-tools`

Now I want to uninstall it. So I entered the following command:
`npm --vcc-build-tools-parameters='[""/Uninstall""]' install --global windows-build-tools`

But I am unable to uninstall it. I get the following output:

```
C:\WINDOWS\system32>npm --vcc-build-tools-parameters='[""/Uninstall""]' install --global windows-build-tools

> windows-build-tools@1.3.2 postinstall C:\Users\pkim\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.13.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.13.msi. Saved to C:\Users\pkim\.windows-build-tools\python-2.7.13.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... -Successfully installed Python 2.7
Waiting for installers... -Successfully installed Visual Studio Build Tools.
+ windows-build-tools@1.3.2
added 128 packages in 72.392s
```
How can I uninstall windows-build-tools? Am I using `/Uninstall` parameter incorrectly?

I looked at #51 and it suggests uninstalling Microsoft Visual C++ Build Tools from `Program & Features` settings in Windows. If so, what is the use of `/Uninstall` parameter?

**Comment by ammonvictor** [comment]
What worked on for me 

1. Navigating to where build tools downloaded the files (cd c:\Users\<YOUR-USER>\.windows-build-tools\) in a cmd with admin rights
2. Ran `"BuildTools_Full.exe /Uninstall /Force /S"`
3. Ran Python installer to uninstall

It's not the most elegant but it gets the job done. The alternative was to script in PowerShell which I know nothing about. See this repository [ps1/launch-installer.ps1](https://github.com/felixrieseberg/windows-build-tools/blob/042c1344762ffde1acac2ebbf4fd8a20cf8c4efa/ps1/launch-installer.ps1#L26-L28) where I adapted the script from

**Comment by oliversalzburg** [comment]
> Am I using /Uninstall parameter incorrectly?

Definitely not. Your command line is *installing* windows-build-tools via `npm`. You're just telling it to pass `/Uninstall` to the build tools while doing so.

You probably want to do what @ammonvictor suggested and `npm uninstall` the module itself.

**Comment by felixrieseberg** [comment]
We sadly don't remove the Visual Studio C++ Build tools or Python when you uninstall. I've updated the title of he issue.

I'm frankly a bit afraid of breaking too many user's environments when we auto-remove anything from the system, but npm's hooks would allow us to run code and therefore remove the C++ Build Tools and/or Python programmatically.

I'd love to see a PR!
