### ISSUE TITLE
Update MSBuild to 2017?

### ISSUE THREAD

**Issue by d3x0r** [felixrieseberg/windows-build-tools#72]
https://blogs.msdn.microsoft.com/vcblog/2016/11/16/introducing-the-visual-studio-build-tools/?__hstc=268264337.e3768af73965ec808da4e31112e1f89f.1512986621574.1512986621574.1512986621574.1&__hssc=268264337.1.1512986621575&__hsfp=1993959496

Could update to 2017 tools (it's only a little over a year since they were released)

**Comment by felixrieseberg** [comment]
We could! It's supported from `npm@5` on, so we should have a new major version that introduces that. It's a good idea though!

**Comment by felixrieseberg** [comment]
Brand new: 2.0-beta uses 2017.

```
npm i --global --production windows-build-tools@2.0.0
```

**Comment by jacobq** [comment]
Is there a document somewhere that summarizes what MS build tool version is recommend to for use with which version of node? (I thought that it was advisable to [keep these "in sync"](https://github.com/nodejs/node-gyp/issues/679#issuecomment-323524986). Is that right?)

**Comment by felixrieseberg** [comment]
I don't think anyone has made a clear authoritative decision. The 2017 build tools install a lot quicker and in theory, it shouldn't _really_ matter which version of the compiler you use. 

That said, I'd love to leave this in beta for a while to make sure that it actually works. 2.0 is on the 2.0 branch - once I get around to it, I'll install a few blank VMs from Modern.ie and will try to compile your typical modules with 2.0 beta. If that all works, we might be doing people a service by upgrading.

**Comment by jtatum** [comment]
Might be interesting to get the CI pipeline to install and use windows-build-tools to build those common packages.

**Comment by tdurie24** [comment]
Had the same issue after installing  VS2019 when l already had VS2017. To resolve this l went to my installation and sorted by date for when l installed vs 2019 and uni-stalled the .Net SDK installed on that day.
