### ISSUE TITLE
Could it corrupt VS 2017?

### ISSUE THREAD

**Issue by thorn0** [felixrieseberg/windows-build-tools#73]
I've been using VS 2017 Community (15.5.2) only for .NET development. When I installed the C++ part of it, I immediately faced [this issue](https://developercommunity.visualstudio.com/content/problem/177094/cant-create-c-project-1.html). Could it be caused by having installed this package? I tried the repair option in the VS installer, tried to uninstall it and install again. Neither helped. I use Windows 7 Professional x64 SP1. A very basic flow is broken in VS, and I have no idea how to fix it.

**Comment by felixrieseberg** [comment]
Hmmmm, possible, but unlikely. I wouldn't put it past Visual Studio to freak out the moment you install a new component, but the build tools installer should do exactly that - install C++ and disappear without breaking anything. I'm very sorry.

In addition, we're installing the 2015 Build Tools, so it should double not touch your VS 2017. `windows-build-tools` uses the Visual C++ Build Tools directly from Microsoft (http://landinghub.visualstudio.com/visual-cpp-build-tools), I'd be in [touch with Microsoft and their support](https://www.visualstudio.com/vs/support/).
