### ISSUE TITLE
Feature request - Python 64-bit on Windows 64-bit

### ISSUE THREAD

**Issue by jvmahon** [felixrieseberg/windows-build-tools#74]
It would be helpful to have Python 64 bit installed on 64 bit versions of windows. To see if I could get this owrking, I've tried to alter the code in the "constants.js" file to do this based on the arch value (see forked repository at github.com/jvmahon/windows-build-tools), but when I then try to install I get the message "If you want to install the Windows Build Tools, you don't want to run "npm install" from the repo." and nothing seems to install. Any thoughts on what I've done wrong? In any case, if this capability could be incorporated into the  master tool, that would be helpful.

**Comment by felixrieseberg** [comment]
Oh, good idea! Would you mind making a PR? You were probably on the right track!

Before uploading to `npm`, we run `npm run build`, which will create a new `lib` folder. If you never ran a build process, the `lib` folder warns you, the developer, that you almost accidentally installed new build tools 😅

**Comment by jvmahon** [comment]
O.K., I did a PR for my changes to constants.js though since I didn't actually get it to work, it does, of course, need checking to confirm.

**Comment by felixrieseberg** [comment]
It looks like this works now!
