### ISSUE TITLE
Fatal error C1083 when building with MSBuild.exe

### ISSUE THREAD

**Issue by mhcgolds** [felixrieseberg/windows-build-tools#78]
I'm having hard times trying to build some packages in my current dev environment(Win10 + VS2015, used for Asp.Net development), so I decided give a try on this lib. I started a VM with a brand new Win10 x64 installation, node 9.1.0(npm 5.5.1) and no other development library installed(no VS, no .Net or SDK etc).

After installation using `npm install --global --production windows-build-tools`, I cloned my repo and exec `npm install`. One of the project dependencies is [edge-cs](https://github.com/tjanczuk/edge-cs), which builds during the installation. Its build proccess gives me the below error:

> C:\Users\Marcio\Documents\GAtec.Mapper2>npm install
> 
> > edge-cs@1.2.1 install C:\Users\Marcio\Documents\GAtec.Mapper2\node_modules\edge-cs
> > node tools/install.js
> 
> 
> > edge-js@9.3.2 install C:\Users\Marcio\Documents\GAtec.Mapper2\node_modules\edge-js
> > node tools/install.js
> 
> Success: platform check for edge.js: node.js x64 v9.1.0
> 
> > mapper2@1.0.0 install C:\Users\Marcio\Documents\GAtec.Mapper2
> > node-gyp rebuild
> 
> 
> C:\Users\Marcio\Documents\GAtec.Mapper2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Warning: Missing input files:
> C:\Users\Marcio\Documents\GAtec.Mapper2\build\..\src\binding.cc
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   binding.cc
> c1xx : fatal error C1083: Cannot open source file: '..\src\binding.cc': No such file or directory [C:\Users\Marcio\Docu
> ments\GAtec.Mapper2\build\binding.vcxproj]
>   win_delay_load_hook.cc
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:135:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
> gyp ERR! System Windows_NT 10.0.10240
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Marcio\Documents\GAtec.Mapper2
> gyp ERR! node -v v9.1.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! mapper2@1.0.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mapper2@1.0.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Marcio\AppData\Roaming\npm-cache\_logs\2018-01-30T13_09_00_004Z-debug.log

What could be the problem? Thank you.

**Comment by felixrieseberg** [comment]
Hey @mhcgolds! Reading the log, you managed to install build tools correctly - msbuild runs and it can find all the system libraries it needs.

However, this line here indicates that something is wrong with `node-egde` or your individual project:

```
Warning: Missing input files:
C:\Users\Marcio\Documents\GAtec.Mapper2\build..\src\binding.cc
```

I feel like this was meant to be a different path, the `build..` in particular looks suspicious. I'd recommend asking over in `node-edge`, I don't think we can help here.
