### ISSUE TITLE
AppVeyor build issues with 1.4.0

### ISSUE THREAD

**Issue by kittaakos** [felixrieseberg/windows-build-tools#82]
Our build started to fail with the 1.4.0 release. The build hangs after downloading the python installer. When I switch back to the 1.3.2 version, then python-2.7.13 is installed. That [works](https://ci.appveyor.com/project/kittaakos/theia/build/1.0.2158).
With the python-2.7.14 installer, it [fails](https://ci.appveyor.com/project/kittaakos/theia/build/1.0.2156).

It could be due to one of the recent AppVeyor default image [changes](https://www.appveyor.com/updates/2018/01/23/) or specific to our [configuration](https://github.com/theia-ide/theia/blob/master/appveyor.yml). Could you please advise? By the way, if you need help, assistance investigating the problem, let me know.

**Comment by pmacn** [comment]
I've opened PR #81 for the python installer issue.

**Comment by felixrieseberg** [comment]
Thanks to @pmacn and @jacobq - they're the true heroes and fixed this. Use `windows-build-tools@1.4.2` and you should be good. Sorry for the trouble!

**Comment by kittaakos** [comment]
Thank you for the fix, I can confirm; AppVeyor works perfectly with `1.4.2`.

Does anyone know why the [build with node `v4.0.0` fails](https://ci.appveyor.com/project/felixrieseberg/windows-build-tools/build/job/gy91r1kwo6cecyvt)? I have tried to reproduce it on my Windows image using node `v4.0.0` but, I was unable to reproduce the failure. Thanks!

```
$ node --version && npm --version && npm install --ignore-scripts && npm run test
v4.0.0
2.14.2

> windows-build-tools@1.4.2 test C:\Users\kittaakos\dev\windows-build-tools
> standard "src/*.js" && npm run build && mocha


> windows-build-tools@1.4.2 build C:\Users\kittaakos\dev\windows-build-tools
> babel src -d lib

src\compatible.js -> lib\compatible.js
src\constants.js -> lib\constants.js
src\download.js -> lib\download.js
src\environment.js -> lib\environment.js
src\index.js -> lib\index.js
src\install\index.js -> lib\install\index.js
src\install\launch.js -> lib\install\launch.js
src\install\tailer.js -> lib\install\tailer.js
src\utils.js -> lib\utils.js


  DownloadTools
    downloadTools (installer)
Downloaded BuildTools_Full.exe. Saved to C:\Users\kittaakos\.windows-build-tools\BuildTools_Full.exe.
      √ should attempt to download the installer (765ms)

  Environment
    √ should attempt to lauch the environment script
    √ should attempt to lauch the environment script with the add to path variable

  Install - Launch
    √ should attempt to lauch the installer script

  Install - Tailer
    √ should register the location of the logfile
    √ waitForLogFile() should resolve when the logfile exists


  6 passing (796ms)
```

BTW, please note the typo in in the spec descriptions: `lauch` -> `launch`.

**Comment by jacobq** [comment]
@kittaakos I believe that error is indicating that node 4.x does not understand/support [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). 
See http://node.green/#ES2015-syntax-destructuring--declarations

Basically, instead of `const { x } = { x: 10 }` you used to have to do `var temp = { x: 10 }; var x = temp.x`

```
const { getWorkDirectory } = require('./get-work-dir')
      ^
SyntaxError: Unexpected token {
```

**Comment by kittaakos** [comment]
Thanks, @jacobq! Do you happen to know why didn't it fail on my Windows image although I set my node version to `4.0.0`? I would like to understand what was the difference between the AppVeyor node and my environment but apparently, I am missing something. Cheers!

**Comment by jacobq** [comment]
@kittaakos I think I was editing my comment as you were writing your reply. The difference is most likely due to which revision of the code you were actually testing. AppVeyor was testing a PR for the 2.0 branch, which hit a problem with `src\utils\get-build-tools-installer-path.js` meanwhile your results show testing of `src\utils.js -> lib\utils.js`, which suggests to me that you are most likely on a different git branch, e.g. `master`.

**Comment by kittaakos** [comment]
Makes sense, that's why I was not finding that module. Thank you for the explanation!

**Comment by pronebird** [comment]
FYI: VC build tools are pre-installed on Appveyor including Python 2.7 if you use the MSVC 2015 Image or newer. There is no need to use windows-build-tools per se.
