### ISSUE TITLE
Python Installer stopped working since last two days

### ISSUE THREAD

**Issue by nigilan** [felixrieseberg/windows-build-tools#85]
Team,

Before a week, running 'npm install windows-build-tools' successfully installed python27 inside the windows-build-tools folder. But, since Feb 3, npm is stuck  while installing python but other steps are successful. Any ways to resolve this issue ?

**Comment by felixrieseberg** [comment]
I’m afraid that I broke something. Does version 1.3.2 still work for you?

Also, could you check enable debug mode? I’d love to know if what we’re logging. Using Poweshell, you could do so with `$env:DEBUG="windows-build-tools"`.

**Comment by Aberrier** [comment]
I have the same issue and adding $env:DEBUG="windows-build-tools" on a PowerShell console didn't work for me.

**Comment by nigilan** [comment]
@felixrieseberg Thanks for prompt reply. Will revert back with details.

**Comment by nigilan** [comment]
Environment : Windows 10 - 64 bit

1. windows-build-tools@1.3.2 is successful. No issues there. 
2. I enabled the debug mode and ran 'npm install windows-build-tools' and it is also working well. 

I cannot replicate the issue now. So, can I go ahead and close this issue ? 

Thanks.
